export const enrolledCourses = [
  {
    code: "CSE101",
    name: "Introduction to Computer Science",
  },
  {
    code: "ENG201",
    name: "Advanced English Composition",
  },
  {
    code: "MATH301",
    name: "Calculus III",
  },
];

export const courses = [
  {
    code: "CSE101",
    name: "Introduction to Computer Science",
    students: ["CMSID1", "CMSID5", "CMSID9"],
  },
  {
    code: "ENG201",
    name: "Advanced English Composition",
    students: ["CMSID2", "CMSID6", "CMSID10"],
  },
  {
    code: "MATH301",
    name: "Calculus III",
    students: ["CMSID3", "CMSID7"],
  },
  {
    code: "HIST401",
    name: "World History: 20th Century",
    students: ["CMSID4", "CMSID8"],
  },
  {
    code: "PHYS501",
    name: "Quantum Physics",
    students: [],
  },
  {
    code: "CHEM601",
    name: "Organic Chemistry",
    students: [],
  },
  {
    code: "PSYC701",
    name: "Introduction to Psychology",
    students: [],
  },
  {
    code: "BIO801",
    name: "Cell Biology",
    students: [],
  },
  {
    code: "ART901",
    name: "Introduction to Art History",
    students: [],
  },
  {
    code: "ECON1001",
    name: "Principles of Microeconomics",
    students: [],
  },
  {
    code: "SOC1101",
    name: "Introduction to Sociology",
    students: [],
  },
  {
    code: "PHIL1201",
    name: "Introduction to Philosophy",
    students: [],
  },
  {
    code: "STAT1301",
    name: "Introduction to Statistics",
    students: [],
  },
  {
    code: "ANTH1401",
    name: "Cultural Anthropology",
    students: [],
  },
  {
    code: "LANG1501",
    name: "Spanish Language I",
    students: [],
  },
  {
    code: "THEA1601",
    name: "Introduction to Theatre",
    students: [],
  },
  {
    code: "POLI1701",
    name: "Introduction to Political Science",
    students: [],
  },
  {
    code: "GEOG1801",
    name: "Physical Geography",
    students: [],
  },
  {
    code: "BUS1901",
    name: "Introduction to Business",
    students: [],
  },
  {
    code: "PHYS2001",
    name: "Classical Mechanics",
    students: [],
  },
  {
    code: "CHEM2101",
    name: "Inorganic Chemistry",
    students: [],
  },
  {
    code: "MATH2201",
    name: "Linear Algebra",
    students: [],
  },
  {
    code: "BIO2301",
    name: "Genetics",
    students: [],
  },
  {
    code: "PSYC2401",
    name: "Abnormal Psychology",
    students: [],
  },
  {
    code: "CSE2501",
    name: "Data Structures and Algorithms",
    students: [],
  },
  {
    code: "SOC2701",
    name: "Sociological Theory",
    students: [],
  },
  {
    code: "PHIL2901",
    name: "Ethics",
    students: [],
  },
  {
    code: "LANG3101",
    name: "French Language II",
    students: [],
  },
  {
    code: "ART3301",
    name: "Modern Art",
    students: [],
  },
  {
    code: "ECON3601",
    name: "Macroeconomics",
    students: [],
  },
];

export const students = [
  {
    cmsId: "CMSID1",
    firstName: "John",
    lastName: "Doe",
    address: "123 Main St",
    city: "New York",
    phoneNumber: "555-1234",
    email: "john.doe@example.com",
    program: "Computer Science",
  },
  {
    cmsId: "CMSID2",
    firstName: "Jane",
    lastName: "Smith",
    address: "456 Park Ave",
    city: "Los Angeles",
    phoneNumber: "555-5678",
    email: "jane.smith@example.com",
    program: "Engineering",
  },
  {
    cmsId: "CMSID3",
    firstName: "Michael",
    lastName: "Johnson",
    address: "789 Elm St",
    city: "Chicago",
    phoneNumber: "555-9012",
    email: "michael.johnson@example.com",
    program: "Business",
  },
  {
    cmsId: "CMSID4",
    firstName: "Emily",
    lastName: "Davis",
    address: "321 Oak Ave",
    city: "San Francisco",
    phoneNumber: "555-3456",
    email: "emily.davis@example.com",
    program: "Psychology",
  },
  {
    cmsId: "CMSID5",
    firstName: "David",
    lastName: "Wilson",
    address: "987 Elm St",
    city: "New York",
    phoneNumber: "555-7890",
    email: "david.wilson@example.com",
    program: "Computer Science",
  },
  {
    cmsId: "CMSID6",
    firstName: "Emma",
    lastName: "Anderson",
    address: "654 Park Ave",
    city: "Los Angeles",
    phoneNumber: "555-1234",
    email: "emma.anderson@example.com",
    program: "Engineering",
  },
  {
    cmsId: "CMSID7",
    firstName: "Daniel",
    lastName: "Johnson",
    address: "321 Main St",
    city: "Chicago",
    phoneNumber: "555-5678",
    email: "daniel.johnson@example.com",
    program: "Business",
  },
  {
    cmsId: "CMSID8",
    firstName: "Olivia",
    lastName: "Brown",
    address: "789 Park Ave",
    city: "San Francisco",
    phoneNumber: "555-9012",
    email: "olivia.brown@example.com",
    program: "Psychology",
  },
  {
    cmsId: "CMSID9",
    firstName: "Sophia",
    lastName: "Taylor",
    address: "123 Elm St",
    city: "New York",
    phoneNumber: "555-3456",
    email: "sophia.taylor@example.com",
    program: "Computer Science",
  },
  {
    cmsId: "CMSID10",
    firstName: "Ethan",
    lastName: "Martin",
    address: "456 Park Ave",
    city: "Los Angeles",
    phoneNumber: "555-7890",
    email: "ethan.martin@example.com",
    program: "Engineering",
  },
];
